---
version: '3.4'
volumes:
  fedora:
  db:
  solr_repo:
  solr_index:
services:
  fedora:
    image: nulib/fcrepo4
    volumes:
    - fedora:/data
    ports:
    - 8986:8080
  db:
    image: healthcheck/postgres:alpine
    volumes:
    - db:/data
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5433:5432
  solr_repo:
    image: solr:7.2-alpine
    ports:
    - 8983:8983
    volumes:
    - solr_repo:/opt/solr/server/solr/mycores
    - "../../solr:/solr_config"
    entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - blacklight-core
    - "/solr_config/config"
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
